[2025-03-02T12:36:39.320+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-02T12:36:39.343+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: redshift_to_s3_dag.execute_repeat_buyers manual__2025-03-02T12:36:38.168098+00:00 [queued]>
[2025-03-02T12:36:39.352+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: redshift_to_s3_dag.execute_repeat_buyers manual__2025-03-02T12:36:38.168098+00:00 [queued]>
[2025-03-02T12:36:39.353+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-02T12:36:39.369+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): execute_repeat_buyers> on 2025-03-02 12:36:38.168098+00:00
[2025-03-02T12:36:39.380+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=15549) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-02T12:36:39.382+0000] {standard_task_runner.py:72} INFO - Started process 15560 to run task
[2025-03-02T12:36:39.381+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'redshift_to_s3_dag', 'execute_repeat_buyers', 'manual__2025-03-02T12:36:38.168098+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/final_aggregation_dag.py', '--cfg-path', '/tmp/tmpglcn3yx2']
[2025-03-02T12:36:39.384+0000] {standard_task_runner.py:105} INFO - Job 166: Subtask execute_repeat_buyers
[2025-03-02T12:36:39.402+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-02T12:36:39.444+0000] {task_command.py:467} INFO - Running <TaskInstance: redshift_to_s3_dag.execute_repeat_buyers manual__2025-03-02T12:36:38.168098+00:00 [running]> on host 22871c84ed32
[2025-03-02T12:36:39.555+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='redshift_to_s3_dag' AIRFLOW_CTX_TASK_ID='execute_repeat_buyers' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T12:36:38.168098+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T12:36:38.168098+00:00'
[2025-03-02T12:36:39.556+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-02T12:36:41.788+0000] {logging_mixin.py:190} INFO - Error executing query repeat_buyers: syntax error at or near "#" in context "BY purchase_count DESC
    #", at line 8, column 5
LINE 8:     # 
            ^
[2025-03-02T12:36:41.790+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-02T12:36:41.803+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-02T12:36:41.804+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=redshift_to_s3_dag, task_id=execute_repeat_buyers, run_id=manual__2025-03-02T12:36:38.168098+00:00, execution_date=20250302T123638, start_date=20250302T123639, end_date=20250302T123641
[2025-03-02T12:36:41.862+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-02T12:36:41.894+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-02T12:36:41.896+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
