[2025-03-02T12:38:19.178+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-02T12:38:19.199+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: redshift_to_s3_dag.execute_repeat_buyers manual__2025-03-02T12:38:18.015435+00:00 [queued]>
[2025-03-02T12:38:19.209+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: redshift_to_s3_dag.execute_repeat_buyers manual__2025-03-02T12:38:18.015435+00:00 [queued]>
[2025-03-02T12:38:19.210+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-02T12:38:19.227+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): execute_repeat_buyers> on 2025-03-02 12:38:18.015435+00:00
[2025-03-02T12:38:19.237+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=15658) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-02T12:38:19.239+0000] {standard_task_runner.py:72} INFO - Started process 15666 to run task
[2025-03-02T12:38:19.238+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'redshift_to_s3_dag', 'execute_repeat_buyers', 'manual__2025-03-02T12:38:18.015435+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/final_aggregation_dag.py', '--cfg-path', '/tmp/tmpilx0b6t5']
[2025-03-02T12:38:19.241+0000] {standard_task_runner.py:105} INFO - Job 169: Subtask execute_repeat_buyers
[2025-03-02T12:38:19.261+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-02T12:38:19.303+0000] {task_command.py:467} INFO - Running <TaskInstance: redshift_to_s3_dag.execute_repeat_buyers manual__2025-03-02T12:38:18.015435+00:00 [running]> on host 22871c84ed32
[2025-03-02T12:38:19.416+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='redshift_to_s3_dag' AIRFLOW_CTX_TASK_ID='execute_repeat_buyers' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T12:38:18.015435+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T12:38:18.015435+00:00'
[2025-03-02T12:38:19.418+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-02T12:38:21.915+0000] {logging_mixin.py:190} INFO - Error executing query repeat_buyers: syntax error at or near "#" in context "BY purchase_count DESC
    #", at line 8, column 5
LINE 8:     # 
            ^
[2025-03-02T12:38:21.917+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-02T12:38:21.932+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-02T12:38:21.933+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=redshift_to_s3_dag, task_id=execute_repeat_buyers, run_id=manual__2025-03-02T12:38:18.015435+00:00, execution_date=20250302T123818, start_date=20250302T123819, end_date=20250302T123821
[2025-03-02T12:38:22.005+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-02T12:38:22.017+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
