[2025-03-01T03:34:53.063+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-01T03:34:53.122+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_data_transformation.transform_s3_data scheduled__2025-02-28T00:00:00+00:00 [queued]>
[2025-03-01T03:34:53.154+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_data_transformation.transform_s3_data scheduled__2025-02-28T00:00:00+00:00 [queued]>
[2025-03-01T03:34:53.155+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-01T03:34:53.315+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): transform_s3_data> on 2025-02-28 00:00:00+00:00
[2025-03-01T03:34:53.326+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=172) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-01T03:34:53.328+0000] {standard_task_runner.py:72} INFO - Started process 184 to run task
[2025-03-01T03:34:53.331+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 's3_data_transformation', 'transform_s3_data', 'scheduled__2025-02-28T00:00:00+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/transformation_dag.py', '--cfg-path', '/tmp/tmp2zc0_0yk']
[2025-03-01T03:34:53.337+0000] {standard_task_runner.py:105} INFO - Job 86: Subtask transform_s3_data
[2025-03-01T03:34:53.378+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-01T03:34:53.495+0000] {task_command.py:467} INFO - Running <TaskInstance: s3_data_transformation.transform_s3_data scheduled__2025-02-28T00:00:00+00:00 [running]> on host ba37d1932f36
[2025-03-01T03:34:53.499+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-01T03:34:54.065+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_data_transformation' AIRFLOW_CTX_TASK_ID='transform_s3_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-28T00:00:00+00:00'
[2025-03-01T03:34:54.067+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-01T03:35:06.780+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-01T03:35:06.795+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-01T03:35:06.796+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=s3_data_transformation, task_id=transform_s3_data, run_id=scheduled__2025-02-28T00:00:00+00:00, execution_date=20250228T000000, start_date=20250301T033453, end_date=20250301T033506
[2025-03-01T03:35:06.864+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-01T03:35:06.877+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
