[2025-03-01T18:32:34.971+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-01T18:32:34.997+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: redshift_query_dag.execute_repeat_buyers manual__2025-03-01T18:32:25.832699+00:00 [queued]>
[2025-03-01T18:32:35.008+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: redshift_query_dag.execute_repeat_buyers manual__2025-03-01T18:32:25.832699+00:00 [queued]>
[2025-03-01T18:32:35.008+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-01T18:32:35.022+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): execute_repeat_buyers> on 2025-03-01 18:32:25.832699+00:00
[2025-03-01T18:32:35.030+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6308) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-01T18:32:35.032+0000] {standard_task_runner.py:72} INFO - Started process 6310 to run task
[2025-03-01T18:32:35.031+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'redshift_query_dag', 'execute_repeat_buyers', 'manual__2025-03-01T18:32:25.832699+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/final_aggregation_dag.py', '--cfg-path', '/tmp/tmpbhm0zzuc']
[2025-03-01T18:32:35.033+0000] {standard_task_runner.py:105} INFO - Job 118: Subtask execute_repeat_buyers
[2025-03-01T18:32:35.049+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-01T18:32:35.088+0000] {task_command.py:467} INFO - Running <TaskInstance: redshift_query_dag.execute_repeat_buyers manual__2025-03-01T18:32:25.832699+00:00 [running]> on host 763fac820cd7
[2025-03-01T18:32:35.189+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='redshift_query_dag' AIRFLOW_CTX_TASK_ID='execute_repeat_buyers' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T18:32:25.832699+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-01T18:32:25.832699+00:00'
[2025-03-01T18:32:35.191+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-01T18:32:37.528+0000] {logging_mixin.py:190} INFO - Error executing query: relation "sales_data" does not exist
[2025-03-01T18:32:37.529+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-01T18:32:37.538+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-01T18:32:37.539+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=redshift_query_dag, task_id=execute_repeat_buyers, run_id=manual__2025-03-01T18:32:25.832699+00:00, execution_date=20250301T183225, start_date=20250301T183234, end_date=20250301T183237
[2025-03-01T18:32:37.595+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-01T18:32:37.612+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-01T18:32:37.613+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
